feat: create coverage badge

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,14 +40,34 @@ jobs:
             make
             if [ -f ./test/RunAllTests ]; then ./test/RunAllTests; else echo "Test binary not found! Skipping test run."; fi
             Xvfb :99 -screen 0 1366x768x24 &
-            make coverage_report || echo "Coverage report target not found."
+            make coverage_report | tee coverage_output.log   || echo "Coverage report target not found."
+
       - name: Upload build artifacts
         uses: actions/upload-artifact@v4
         with:
           name: firmware-build
           path: |
             ${{ github.workspace }}/firmware/build/
+      
+      - name: Extract Coverage Percentage
+        run: |
+          LINE_COV=$(grep "lines......:" build/coverage_output.log | tail -1 | awk '{print $2}')
+          echo "COVERAGE=${LINE_COV}" >> $GITHUB_ENV
+          echo "Coverage = ${LINE_COV}"      
+          
+      - name: Generate badge
+        uses: emibcn/badge-action@v2
+        with:
+          label: Coverage
+          status: ${{ env.COVERAGE }}
+          color: green
+          path: coverage-badge.svg
 
+      - name: Commit badge
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: "Update coverage badge"
+          file_pattern: coverage-badge.svg
 
   coverity-scan:
     name: Coverity Scan
