pipline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,19 +75,26 @@ jobs:
             echo "No firmware files found. Skipping build."
             exit 78
           fi
-
       - name: Build with STM32CubeIDE
         run: |
-          find / -iname "st/stm32cubeide_1.17.0" -type d
-          # mkdir -p /home/ws/
-          # echo "Starting STM32CubeIDE headless build..."
-          # $stm32cubeIDE_path --launcher.suppressErrors -nosplash \
-          #   -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
-          #   -build all \
-          #   -importAll  ${workspace_path}/${project_name}/firmware/ \
-          #   -data /home/ws/
-          # echo "Build completed successfully."
-          # cd firmware && ls -la
+          mkdir -p /home/ws/
+          echo "Checking STM32CubeIDE installation..."
+          if [ ! -x "/opt/st/stm32cubeide_1.17.0/stm32cubeide" ]; then
+            echo "Error: STM32CubeIDE not found at /opt/st/stm32cubeide_1.17.0/stm32cubeide"
+            exit 1
+          fi
+          
+          echo "Starting STM32CubeIDE headless build..."
+          /opt/st/stm32cubeide_1.17.0/stm32cubeide \
+            --launcher.suppressErrors -nosplash \
+            -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
+            -build all \
+            -importAll "${workspace_path}/${project_name}/firmware/" \
+            -data /home/ws/
+
+          echo "Build completed successfully."
+          cd firmware && ls -la
+
 
       - uses: actions/upload-artifact@v4
         with:
